set_property SRC_FILE_INFO {cfile:O:/ENGS31/vgaDisplay/vgaDisplay.srcs/constrs_1/new/ENGS31_Constraints_Template.xdc rfile:../../../vgaDisplay.srcs/constrs_1/new/ENGS31_Constraints_Template.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk_ext_port]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports {vgaR_ext_port}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {vgaB_ext_port}]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {vgaG_ext_port}]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports Hsync_ext_port]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports Vsync_ext_port]
